<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Donation;

/**
 * AssosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssosRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $id
     * @return array
     *
     * Retourne les associations liées à une catégorie
     */
    public function getByCategory($id)
    {
        $queryBuilder = $this->createQueryBuilder('assos');

        $queryBuilder
            ->leftJoin('assos.categories', 'category')
            ->where('category.id = :id')
            ->setParameter('id', $id);

        return $queryBuilder->getQuery()->getResult();
    }


    public function getByUserDonation($user)
    {
        $queryBuilder = $this->createQueryBuilder('assos');

        $queryBuilder
            ->leftJoin('assos.donations', 'don')
            ->leftJoin('don.user', 'user')

            ->where('don.user = :user')
            ->setParameter('user', $user)

            ->andWhere('don.paymentStatus IN (:status)')
            ->setParameter('status', [Donation::PAY_IN_TRANSFER, Donation::PAY_PROCESSED])

            ->orderBy('don.createdAt', 'DESC');

        return $queryBuilder->getQuery()->getResult();
    }

    public function getGivenAmount($association)
    {
        $queryBuilder = $this->createQueryBuilder('assos');

        $queryBuilder
            ->select('SUM(don.amount)')
            ->leftJoin('assos.donations', 'don')

            ->where('don.assos = :asso')
            ->setParameter('asso', $association);


        return $queryBuilder->getQuery()->getSingleScalarResult();
    }
}
