<?php

namespace AppBundle\Repository;

/**
 * AssosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssosRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $id
     * @return array
     *
     * Retourne les associations liées à une catégorie
     */
    public function getByCategory($id)
    {
        $queryBuilder = $this->createQueryBuilder('assos');

        $queryBuilder
            ->leftJoin('assos.categories', 'category')
            ->where('category.id = :id')
            ->setParameter('id', $id);

        return $queryBuilder->getQuery()->getResult();
    }
}
