<?php

namespace AppBundle\Repository;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $limit
     * @param $minMark
     * @return array
     *
     * Retourne le nombre $limit de Reviews, les plus récentes, ayant une note suppérieur à $minMark
     */
    public function findHomePageReviews($limit, $minMark)
    {
        $queryBuilder = $this->createQueryBuilder('r');

        $queryBuilder
            ->where('r.mark >= :minMark')
            ->setParameter('minMark', $minMark)
            ->orderBy('r.createdAt', 'DESC')
            ->setMaxResults($limit);

        return $queryBuilder->getQuery()->getResult();
    }
}
