imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Définition des variables PHP Global
parameters:
    locale: fr
    # dossier des images d'associations par défaut
    images_dir: '%kernel.project_dir%/web/assets/images/assos/'

    # tableau des montants proposés pour les dons
    array_amount: [1,2,5,10,15,20,25,30,50,100,200]

    # montant du don par défaut
    default_amount: 10


framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    templating:
        engines: ['twig']


# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    # Modifie les class des formulaires avec un template Twig intégré au Bundle
    form_themes: ['bootstrap_4_layout.html.twig']

    # Définition des variables Twig Global
    globals:
        # image par défaut des associations
        ImgAssosDefault: '/assets/images/defaultAssos.jpeg'

        # dossier par défaut des images d'associations
        ImgAssosFolder: '/assets/images/assos/'

        # tableau des montants proposés pour les dons
        array_amount: '%array_amount%'

        # montant du don par défaut
        default_amount: '%default_amount%'


# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

        # Intallation du Bundle https://github.com/beberlei/DoctrineExtensions
        # qui permet de rajouter des méthode DQL telque YEAR() / MONTH() etc.
        dql:
            string_functions:
                MONTH: DoctrineExtensions\Query\Mysql\Month
                YEAR: DoctrineExtensions\Query\Mysql\Year


# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

sensio_framework_extra:
   router:
        annotations: false

# Config du FOSUser
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    registration:
        form:
            type: AppBundle\Form\RegistrationFormType
        #confirmation:
            #enabled: true

# Config du Bundle PayPal
beelab_paypal:
    username: "%paypal_username%"
    password: "%paypal_password%"
    signature: "%paypal_signature%"
    return_route: user_payment_success
    cancel_route: user_payment_cancel
    test_mode: "%kernel.debug%"